create table address (id bigint not null auto_increment, created_date datetime, last_modified_date datetime, first_line varchar(255), postcode varchar(255), second_line varchar(255), primary key (id)) engine=InnoDB;
create table administrators (id bigint not null auto_increment, created_date datetime, last_modified_date datetime, first_name varchar(255), last_name varchar(255), contact_detail_id bigint, primary key (id)) engine=InnoDB;
create table assignment_type (id bigint not null auto_increment, created_date datetime, last_modified_date datetime, description varchar(255), primary key (id)) engine=InnoDB;
create table assignment_type_student_results (assignment_type_id bigint not null, student_results_id bigint not null, primary key (assignment_type_id, student_results_id)) engine=InnoDB;
create table authority (id bigint not null auto_increment, created_date datetime, last_modified_date datetime, permission varchar(255), primary key (id)) engine=InnoDB;
create table contact_detail (id bigint not null auto_increment, created_date datetime, last_modified_date datetime, email varchar(255), phone_number varchar(255), primary key (id)) engine=InnoDB;
create table form_group_list (id bigint not null auto_increment, created_date datetime, last_modified_date datetime, group_name varchar(255), teacher_id bigint, primary key (id)) engine=InnoDB;
create table guardians (id bigint not null auto_increment, created_date datetime, last_modified_date datetime, first_name varchar(255), last_name varchar(255), address_id bigint, contact_detail_id bigint, primary key (id)) engine=InnoDB;
create table login_failure (id bigint not null auto_increment, created_date datetime, last_modified_date datetime, sourceip varchar(255), username_entered varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table login_success (id bigint not null auto_increment, created_date datetime, last_modified_date datetime, sourceip varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table report (id bigint not null auto_increment, created_date datetime, last_modified_date datetime, comments varchar(255), unique_identifier varchar(255), student_id bigint, subject_id bigint, teacher_id bigint, primary key (id)) engine=InnoDB;
create table role (id bigint not null auto_increment, created_date datetime, last_modified_date datetime, role_name varchar(255), primary key (id)) engine=InnoDB;
create table role_authority (role_id bigint not null, authority_id bigint not null, primary key (role_id, authority_id)) engine=InnoDB;
create table srm_root_users (id bigint not null auto_increment, created_date datetime, last_modified_date datetime, first_name varchar(255), last_name varchar(255), contact_detail_id bigint, primary key (id)) engine=InnoDB;
create table student (id bigint not null auto_increment, created_date datetime, last_modified_date datetime, first_name varchar(255), last_name varchar(255), middle_names varchar(255), contact_detail_id bigint, form_group_list_id bigint, teacher_id bigint, primary key (id)) engine=InnoDB;
create table student_guardian (student_id bigint not null, guardian_id bigint not null, primary key (student_id, guardian_id)) engine=InnoDB;
create table student_subjectlist (student_id bigint not null, subjectclasslist_id bigint not null, primary key (student_id, subjectclasslist_id)) engine=InnoDB;
create table student_result (id bigint not null auto_increment, created_date datetime, last_modified_date datetime, comments varchar(255), score varchar(255), student_id bigint, student_task_id bigint, teacher_id bigint, primary key (id)) engine=InnoDB;
create table student_task (id bigint not null auto_increment, created_date datetime, last_modified_date datetime, contributor bit not null, max_score varchar(255), title varchar(255), assignment_type_id bigint, subject_id bigint not null, teacher_uploader_id bigint, primary key (id)) engine=InnoDB;
create table student_task_threshold_list (threshold_list_id bigint not null, student_task_id bigint not null, primary key (student_task_id, threshold_list_id)) engine=InnoDB;
create table subject_class_list (id bigint not null auto_increment, created_date datetime, last_modified_date datetime, group_name varchar(255), subject_id bigint, teacher_id bigint, primary key (id)) engine=InnoDB;
create table subjects (id bigint not null auto_increment, created_date datetime, last_modified_date datetime, subject_name varchar(255), primary key (id)) engine=InnoDB;
create table teacher_subject (teacher_id bigint not null, subject_id bigint not null, primary key (teacher_id, subject_id)) engine=InnoDB;
create table teachers (id bigint not null auto_increment, created_date datetime, last_modified_date datetime, department varchar(255), first_name varchar(255), last_name varchar(255), contact_detail_id bigint, primary key (id)) engine=InnoDB;
create table threshold (id bigint not null auto_increment, created_date datetime, last_modified_date datetime, alphabetical varchar(255), numerical integer not null, unique_id varchar(255), uploader_id bigint, primary key (id)) engine=InnoDB;
create table threshold_list (id bigint not null auto_increment, created_date datetime, last_modified_date datetime, uniqueid varchar(255), uploader_id bigint, primary key (id)) engine=InnoDB;
create table threshold_list_threshold (thresholdlist_id bigint not null, threshold_id bigint not null, primary key (thresholdlist_id, threshold_id)) engine=InnoDB;
create table user (id bigint not null auto_increment, created_date datetime, last_modified_date datetime, account_non_expired bit, account_non_locked bit, credentials_non_expired bit, enabled bit, password varchar(255), username varchar(255), admin_user_id bigint, guardian_user_id bigint, root_user_id bigint, teacher_user_id bigint, primary key (id)) engine=InnoDB;
create table user_role (user_id bigint not null, role_id bigint not null, primary key (user_id, role_id)) engine=InnoDB;
alter table assignment_type_student_results add constraint UK_39982bissb4g939a8ry45dimx unique (student_results_id);
alter table administrators add constraint FKan1ou4vy0wn92xc3csco1ogei foreign key (contact_detail_id) references contact_detail (id);
alter table assignment_type_student_results add constraint FKbt58542na3rv50cw8g77o9gtw foreign key (student_results_id) references student_result (id);
alter table assignment_type_student_results add constraint FKpmoxif9y6njdu6k5dbl2xqbhq foreign key (assignment_type_id) references assignment_type (id);
alter table form_group_list add constraint FKt01wdbsksvarlj2545rok7cfm foreign key (teacher_id) references teachers (id);
alter table guardians add constraint FKd20g3ng3kbtldj12uwnlhqiyl foreign key (address_id) references address (id);
alter table guardians add constraint FKbsjm6mhydwb3tpfnnfqluo5xt foreign key (contact_detail_id) references contact_detail (id);
alter table login_failure add constraint FK7yuqycsl6io9aivn03yr2hiia foreign key (user_id) references user (id);
alter table login_success add constraint FKbhp83p080sodt4vrtcgbsdl9e foreign key (user_id) references user (id);
alter table report add constraint FKl6ssom7r83r8bofvdkjkp18pj foreign key (student_id) references student (id);
alter table report add constraint FK9ifs5m239o2dj1xcrilna249s foreign key (subject_id) references subjects (id);
alter table report add constraint FKhqm4ppa6v9507g3qi8941jloq foreign key (teacher_id) references teachers (id);
alter table role_authority add constraint FKqbri833f7xop13bvdje3xxtnw foreign key (authority_id) references authority (id);
alter table role_authority add constraint FK2052966dco7y9f97s1a824bj1 foreign key (role_id) references role (id);
alter table srm_root_users add constraint FKmkbew2meqmtbbktghj7mc45w3 foreign key (contact_detail_id) references contact_detail (id);
alter table student add constraint FK1r05weode9bw3223x9kxnrgb foreign key (contact_detail_id) references contact_detail (id);
alter table student add constraint FK88ci72yl4gbgu716ea9h65mmp foreign key (form_group_list_id) references form_group_list (id);
alter table student add constraint FK15qvgqoejujc0e1mme59oxaew foreign key (teacher_id) references teachers (id);
alter table student_guardian add constraint FKilnqkwg0m1t2e7kc01lsmo2ib foreign key (guardian_id) references guardians (id);
alter table student_guardian add constraint FK3a2n27up9s1eotod8d63j3xyl foreign key (student_id) references student (id);
alter table student_subjectlist add constraint FKh8ce89ukrefyui23l608vaue3 foreign key (subjectclasslist_id) references subject_class_list (id);
alter table student_subjectlist add constraint FKnf4tie4s6hf8mf9spqymxamqa foreign key (student_id) references student (id);
alter table student_result add constraint FKsl2963tgdjk19e69pixkjogca foreign key (student_id) references student (id);
alter table student_result add constraint FKmgakr5xndukh0qtwufd62alt1 foreign key (student_task_id) references student_task (id);
alter table student_result add constraint FKer09tbockdcynbybd93f5k9xu foreign key (teacher_id) references teachers (id);
alter table student_task add constraint FKr59dxf23jhf226vm7fsi25ajd foreign key (assignment_type_id) references assignment_type (id);
alter table student_task add constraint FKcqjhhki1h7b1hkfa35ydirl1o foreign key (subject_id) references subjects (id);
alter table student_task add constraint FKdhixnun13vay7aoa3o93bowda foreign key (teacher_uploader_id) references teachers (id);
alter table student_task_threshold_list add constraint FK8tet6liqp4k8058yfk6suc3wd foreign key (student_task_id) references student_task (id);
alter table student_task_threshold_list add constraint FKdxd2illc2vrx5e0ak7ih7la10 foreign key (threshold_list_id) references threshold_list (id);
alter table subject_class_list add constraint FKf78kjac0w6nwmf6mcjo1c9myl foreign key (subject_id) references subjects (id);
alter table subject_class_list add constraint FKbqyoj1q588q3oi22ege5lhs3p foreign key (teacher_id) references teachers (id);
alter table teacher_subject add constraint FKlbm776mn6b4lu6hsdf29unq6x foreign key (subject_id) references subjects (id);
alter table teacher_subject add constraint FKa1d1n8m8pv7rr2493x6jp3f3q foreign key (teacher_id) references teachers (id);
alter table teachers add constraint FKe4mgvr2g7umulytevxxb6bxb1 foreign key (contact_detail_id) references contact_detail (id);
alter table threshold add constraint FKjdvoxxjotjqm0tg13d2quwiwx foreign key (uploader_id) references teachers (id);
alter table threshold_list add constraint FKr4orretqk98ifmb0wxf4opyie foreign key (uploader_id) references teachers (id);
alter table threshold_list_threshold add constraint FKjaprn4sp4av4nmkc7ypvmvx4u foreign key (threshold_id) references threshold (id);
alter table threshold_list_threshold add constraint FKsd7kxwgmteyw9swxjsk92i9af foreign key (thresholdlist_id) references threshold_list (id);
alter table user add constraint FKenx1bft5hbkathlirjg3trvce foreign key (admin_user_id) references administrators (id);
alter table user add constraint FK4nknpk4md8snh6ejaue3i84su foreign key (guardian_user_id) references guardians (id);
alter table user add constraint FKc0fhmljlqp3iv7sa9pf9m3pyn foreign key (root_user_id) references srm_root_users (id);
alter table user add constraint FKimtdxo5jjpt5st5immn8ax9ex foreign key (teacher_user_id) references teachers (id);
alter table user_role add constraint FKa68196081fvovjhkek5m97n3y foreign key (role_id) references role (id);
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user (id);
